#!/bin/bash
paru -S neofetch wl-clipboard foot ttf-iosevka-nerd xdg-user-dirs nwg-look tldr github-cli arc-gtk-theme htop man-db sway swaybg wofi playerctl stow tree thorium-browser-bin vlc qt5-wayland qt6-wayland brightnessctl wget zsh
git config --global user.name "Zack Waterman"
git config --global user.email "zackgwaterman@gmail.com"
git config --global init.defaultBranch main

# Surface
curl -s https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | sudo pacman-key --add -
sudo pacman-key --finger 56C464BAAC421453
sudo pacman-key --lsign-key 56C464BAAC421453
echo -e "\n[linux-surface]\nServer = https://pkg.surfacelinux.com/arch/" | sudo tee -a /etc/pacman.conf
paru
paru -S linux-surface linux-surface-headers iptsd libwacom-surface
sudo grub-mkconfig -o /boot/grub/grub.cfg
